spring:
  resources:
    static-locations: classpath:/

  datasource:
    url: jdbc:h2:../h2test;mode=PostgreSQL;database_to_lower=true
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

alacrity:
  alacrityVersion: v1.0.0 Test
  resourceBootstrapCSS: https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css
  resourceBootstrapJS: https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js
  resourceJQueryJS: https://code.jquery.com/jquery-3.5.1.min.js
  resourcePopperJS: https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js
  resourceMathJaxJS: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=AM_SVG
