spring:
  resources:
    static-locations: classpath:/

  datasource:
    url: jdbc:h2:mem:h2database;mode=PostgreSQL;database_to_lower=true
#    url: jdbc:h2:./h2alacrity;mode=PostgreSQL;database_to_lower=true
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

alacrity:
  alacrityVersion: v1.0.0 Debug
  resourceBootstrapCSS: /public/bootstrap-4.6.0.min.css
  resourceBootstrapJS: /public/bootstrap-4.6.0.min.js
  resourceJQueryJS: /public/jquery-3.5.1.min.js
  resourcePopperJS: /public/popper-1.16.1.min.js
  resourceMathJaxJS: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=AM_SVG
